"""empty message

Revision ID: 8e544528cfd0
Revises: 31f51d2ed6c5
Create Date: 2022-10-21 08:35:16.618593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e544528cfd0'
down_revision = '31f51d2ed6c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('username', sa.String(length=25), nullable=True),
    sa.Column('password', sa.String(length=500), nullable=True),
    sa.Column('access', sa.String(length=120), nullable=True),
    sa.Column('online', sa.String(length=2), nullable=True),
    sa.Column('active', sa.String(length=2), nullable=True),
    sa.Column('role', sa.String(length=2), nullable=True),
    sa.Column('link', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
